
server:
  port: 8080
  servlet:
    context-path: /smart_expense

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/smart_expense_db"
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  signerKey: "UtGJAUqxBKEhcZnt7LRpYshNPEQEbxEQYeE5l6/cnTdjA3TAeEX9AvKq1WAr63Xx"
  valid-duration: 3600 # in seconds
  refreshable-duration: 360000 # in seconds
